library(brazilmaps)
library(sf)
library(maps)
library(mapdata)
library(raster)
library(dplyr)
library(RColorBrewer)
library(shiny)
library(bs4Dash)
library(leaflet)
library(shinyWidgets)
library(shinycssloaders)
library(shinyBS)
library(shinyjs)
library(plotly)
library(RCurl)
library (readr)
library(ggplot2)